site:
  title: model2owl documentation
  start_page: ROOT::index.adoc

antora:
  extensions:
  - require: '@antora/lunr-extension'
    snippet_length: 250


content:
  sources:
#    - url: .
    - url: https://github.com/meaningfy-ws/model2owl-docs
      branches: [ main ]
      start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./docs/supplemental-ui
